### ISSUE TITLE
[CRC-CCITT (Kermit)] Inverted Bytes?

### ISSUE THREAD

**Issue by rtek1000** [meetanthony/crcphp#4]
https://www.lammertbies.nl/comm/info/crc-calculation.html returns: 0x8921

http://www.tahapaksu.com/crc/ returns: 0x8921

https://crccalc.com/ returns: 0x2189

Input data "123456789" (string ASCII)

**Comment by meetanthony** [comment]
> CRC-16/KERMIT
> width=16 poly=0x1021 init=0x0000 refin=true refout=true xorout=0x0000 check=0x2189 residue=0x0000 name="CRC-16/KERMIT"

from http://reveng.sourceforge.net/crc-catalogue/16.htm
